<Project Sdk="MSTest.Sdk/4.4.1">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../OOs.Common.Threading/OOs.Common.Threading.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.GitHubActionsReport" />
  </ItemGroup>

</Project>