using System.Text;

namespace OOs.CommandLine.Generators;

internal static class CodeEmitHelper
{
    internal static void AppendFileHeader(StringBuilder sb)
    {
        sb.Append(
            $"""
            //-------------------------------------------------------------------------------
            // <auto-generated>
            // This code was generated by a tool.
            // Changes to this file may cause incorrect behavior and will be lost
            // if the code is regenerated.
            """);
#if DEBUG
        sb.Append($$"""
            
            // at {{DateTime.UtcNow}}
            
            """);
#endif
        sb.Append($$"""
            // </auto-generated>
            //-------------------------------------------------------------------------------
            
            """);
    }

    internal static void AppendGeneratedCodeAttribute(StringBuilder sb)
    {
        sb.Append(
            $$"""
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{ProductInfo.Product}}", "{{ProductInfo.Version}}")]
            """);
    }
}